-- V1: Migrations para criar tabelas de tb_cadastro e tb_missoes evitando conflito com JPA
CREATE TABLE tb_missoes(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    dificuldade VARCHAR(100),
    rank VARCHAR(100)
);

CREATE TABLE tb_cadastro(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    idade INTEGER,
    email VARCHAR(255) UNIQUE NOT NULL,
    missoes_id BIGINT
);

ALTER TABLE tb_cadastro
ADD CONSTRAINT fk_missoes
FOREIGN KEY(missoes_id)
REFERENCES tb_missoes(id);